site_name: abinit
site_url: https://docs.abinit.org
site_description: Abinit documentation
site_author: The Abinit group
docs_dir: doc

repo_name: github-abinit
repo_url: https://github.com/abinit/abinit/
edit_uri: edit/master/doc/

# If `True`, use `<page_name>/index.hmtl` style files with hyperlinks to
# the directory. If `False`, use `<page_name>.html style file with hyperlinks to the file.
# True generates nicer URLs, but False is useful if browsing the output on a filesystem.
use_directory_urls: True
#use_directory_urls: False

pages:
#- Quick Start: 
#- Home: index.md
- User Guide:
    #- NewUser: guide/new_user.md
    - NewUser: index.md
    - Abinit: guide/abinit.md
    - Aim: guide/aim.md
    - Anaddb: guide/anaddb.md
    - Cut3d: guide/cut3d.md
    - Fold2Bloch: guide/fold2bloch.md
    - Mrgddb: guide/mrgddb.md
    - Mrgscr: guide/mrgscr.md
    - Optic: guide/optic.md
    - Respfn: guide/respfn.md
    - Spacegroup: guide/spacegroup.md
    - Installation:
        - HowTo: installation.md
        - MacOSX: README_MacOSX.md
        - GPUs: README_gpu.md
        - Xlf: README_xlf.md

- Topics:
    - Features: topics/features.md
    - Topic List: topics/index.md
    - topics/Abipy.md
    - topics/APPA.md
    - topics/Artificial.md
    - topics/AtomManipulator.md
    - topics/AtomTypes.md
    - topics/Bader.md
    - topics/Band2eps.md
    - topics/Berry.md
    - topics/BandOcc.md
    - topics/BSE.md
    - topics/ConstrainedPol.md
    - topics/Control.md
    - topics/Coulomb.md
    - topics/CRPA.md
    - topics/crystal.md
    - topics/DFT+U.md
    - topics/DeltaSCF.md
    - topics/DensityPotential.md
    - topics/Dev.md
    - topics/DFPT.md
    - topics/DMFT.md
    - topics/EffMass.md
    - topics/EFG.md
    - topics/Elastic.md
    - topics/ElPhonInt.md
    - topics/ElPhonTransport.md
    - topics/ElecDOS.md
    - topics/ElecBandStructure.md
    - topics/FileFormats.md
    - topics/ForcesStresses.md
    - topics/FrequencyMeshMBPT.md
    - topics/GeoConstraints.md
    - topics/GeoOpt.md
    - topics/Git.md
    - topics/GSintroduction.md
    - topics/GW.md
    - topics/GWls.md
    - topics/Hybrids.md
    - topics/k-points.md
    - topics/LDAminushalf.md
    - topics/LOTF.md
    - topics/MagField.md
    - topics/MagMom.md
    - topics/MolecularDynamics.md
    - topics/multidtset.md
    - topics/nonlinear.md
    - topics/Optic.md
    - topics/Output.md
    - topics/parallelism.md
    - topics/PAW.md
    - topics/PIMD.md
    - topics/Planewaves.md
    - topics/Phonons.md
    - topics/PhononBands.md
    - topics/PhononWidth.md
    - topics/PortabilityNonRegression.md
    - topics/positron.md
    - topics/printing.md
    - topics/PseudosPAW.md
    - topics/q-points.md
    - topics/RandStopPow.md
    - topics/Recursion.md
    - topics/RPACorrEn.md
    - topics/SCFControl.md
    - topics/SCFAlgorithms.md
    - topics/SelfEnergy.md
    - topics/SmartSymm.md
    - topics/spinpolarisation.md
    - topics/STM.md
    - topics/Susceptibility.md
    - topics/TDDFT.md
    - topics/TDepES.md
    - topics/Temperature.md
    - topics/TransPath.md
    - topics/TuningSpeed.md
    - topics/Unfolding.md
    - topics/UnitCell.md
    - topics/vdw.md
    - topics/Verification.md
    - topics/Wannier.md
    - topics/Wavelets.md
    - topics/xc.md
    - External Resources: topics/external_resources.md
- Variables:
    - All Variables: variables/index.md
    - Abinit:
        - Basic: variables/basic.md
        - Bethe-Salpeter: variables/bse.md
        - Developers: variables/dev.md
        - DMFT: variables/dmft.md
        - Electron-Phonon: variables/eph.md
        - Varff: variables/ffield.md
        - File-handling: variables/files.md
        - Geometry: variables/geo.md
        - Ground-State: variables/gstate.md
        - GW: variables/gw.md
        - Internal: variables/internal.md
        - Parallelism: variables/paral.md
        - PAW: variables/paw.md
        - DFPT: variables/dfpt.md
        - Relaxation: variables/rlx.md
        - VdW: variables/vdw.md
        - Wannier90: variables/w90.md
    - Anaddb: variables/anaddb.md
    - Optic: variables/optic.md
    - Aim: variables/aim.md
    - External Parameters: variables/external_parameters.md
    - Statistics: variables/varset_stats.md
- Lessons:
    - Overview: tutorial/index.md
    - Base Tutorials: 
        - Base1: tutorial/base1.md
        - Base2: tutorial/base2.md
        - Base3: tutorial/base3.md
        - Base4: tutorial/base4.md
        - Spin: tutorial/spin.md
    - PAW:
        - PAW1: tutorial/paw1.md
        - PAW2: tutorial/paw2.md
        - PAW3: tutorial/paw3.md
    - DFT_PLUS_U:
        - tutorial/dftu.md
        - tutorial/udet.md
        - tutorial/ucalc_crpa.md
    - DFPT:
        - RF1: tutorial/rf1.md
        - RF2: tutorial/rf2.md
        - Elastic: tutorial/elastic.md
        - tutorial/ffield.md
        - tutorial/nlo.md
    - DMFT: tutorial/dmft.md
    - EPH: 
        - tutorial/eph.md
        - tutorial/tdepes.md
    - Many-Body:
        - GW1: tutorial/gw1.md
        - GW2: tutorial/gw2.md
        - Bethe-Salpeter: tutorial/bse.md
    - Parallelism:
        - Base: tutorial/basepar.md
        - GSPW: tutorial/paral_gspw.md
        - GSWVL: tutorial/paral_gswvl.md
        - DFPT: tutorial/paral_dfpt.md
        - Images: tutorial/paral_images.md
        - Many-Body: tutorial/paral_mbt.md
        - Moldyn: tutorial/paral_moldyn.md
    - tutorial/analysis_tools.md
    - tutorial/fold2bloch.md
    - tutorial/nuc.md
    - tutorial/optic.md
    - tutorial/positron.md
    - tutorial/source_code.md
    - tutorial/tddft.md
    - tutorial/wannier90.md
- Theory:
    - Geometry: theory/geometry.md
    - Spherical Harmonics: theory/spherical_harmonics.md
    - Wavefunctions: theory/wavefunctions.md
    - Noncollinear: theory/noncollinear.md
    - Pseudopotentials: theory/pseudopotentials.md
    - Many-Body Perturbation Theory: theory/mbt.md
    - Bethe-Salpeter: theory/bse.md
    - Documents: theory/documents.md
    - Acknowledgments: theory/acknowledgments.md
    - Bibliography: theory/bibliography.md
- Developers:
    - Abimkdocs: developers/abimkdocs.md
    - Markdown: developers/markdown.md
    - Test Suite: developers/testsuite.md
    - Pseudos: 
        #- psp1: developers/psp1_data.txt
        - psp1: developers/psp1_info.md
        - psp3: developers/psp3_info.md
        - psp45: developers/psp45_info.md
        - psp5: developers/psp5spinorbit_info.md
        - psp6: developers/psp6_info.md
        - psp8: developers/psp8_info.md
    - Code stats: developers/codestats.md
    - Autoconf_examples: developers/autoconf_examples.md
    #- External Resources: developers/external_resources.md
- About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

markdown_extensions:
  - markdown.extensions.meta
  - markdown.extensions.toc:
        permalink: true  # For ¶
        #permalink: "#"
        #separator: "_"
  - markdown.extensions.admonition
  - markdown.extensions.fenced_code 
  - markdown.extensions.codehilite
  - markdown.extensions.smarty
  - markdown.extensions.tables
  - markdown.extensions.def_list
  - markdown.extensions.sane_lists
  - mdx_math:
        enable_dollar_delimiter: True
  #- pymdownx.arithmatex:
        #inline_syntax: ['dollar']
        #block_syntax:  ['dollar', 'begin']
        #insert_as_script: True
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  #- pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols:
        registered: false
        copyright: false
        care_of: false
  - pymdownx.superfences
  - pymdownx.tilde
  # Abinit extensions.
  - abimkdocs.wikilinks
  - abimkdocs.preprocessor
  - abimkdocs.mdx_figcaption
  #- abimkdocs.treepreprocessor
        
#strict: true

theme:
    name: material
    custom_dir: abinit_theme
    logo: images/logo-abinit-2015.png
    favicon: images/favicon.ico
    palette:
        primary: deep orange
        accent: deep orange
    feature:
        tabs: true

plugins:
    - abimkdocs
    #- search    # Deactivated

extra:
    version: 8.9.2
    previous_published_versions: [] #8.2.0
    social:
        - type: github-alt
          link: https://github.com/abinit/abinit
        - type: twitter
          link: https://twitter.com/hashtag/abinit
        - type: facebook
          link: http://www.facebook.com/abinit.org
        - type: youtube
          link: https://www.youtube.com/watch?v=gcbfb_Mteo4

extra_css:
    - css/extra.css
    - css/gallery.css
    - css/my_codehilite.css

extra_javascript:
    - extra_javascript/jquery.dialogextend.min.js
    - extra_javascript/abidocs.js

copyright: Copyright &copy; 2018 The Abinit Group

# Google Analytics
google_analytics: ['UA-116681470-1', 'docs.abinit.org']
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto
